[project]
name = "sir"
version = "0.1.0"
description = "Modelling of an epidemic"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
SIR = "sir:main"
